<?php

use Illuminate\Database\Seeder;
use App\Models\City;

class CitiesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    { 
        $i = 1;
        $cities = [
            [
                'id' => $i++,
                'name_en' => 'Abha',
                'name_ar' => 'ابها',
                'district_id' => 6,
            ],
            [
                'id' => $i++,
                'name_en' => 'Abu Arish',
                'name_ar' => 'ابو عريش',
                'district_id' => 10,
            ],
            [
                'id' => $i++,
                'name_en' => 'Mecca',
                'name_ar' => 'مكة المكرمة',
                'district_id' => 2,
            ],
            [
                'id' => $i++,
                'name_en' => 'Dammam',
                'name_ar' => 'الدمام',
                'district_id' => 5,
            ],
            [
                'id' => $i++,
                'name_en' => 'Hafr Al-Batin',
                'name_ar' => 'حفر الباطن',
                'district_id' => 5,
            ],
            [
                'id' => $i++,
                'name_en' => 'Ehsaa',
                'name_ar' => 'الأحساء',
                'district_id' => 5,
            ],
            [
                'id' => $i++,
                'name_en' => 'Dawadmi',
                'name_ar' => 'الدوادمي',
                'district_id' => 1,
            ],
            [
                'id' => $i++,
                'name_en' => 'addilam',
                'name_ar' => 'الدلم',
                'district_id' => 1,
            ],
            [
                'id' => $i++,
                'name_en' => 'Diriyah',
                'name_ar' => 'الدرعية',
                'district_id' => 2,
            ],
            [
                'id' => $i++,
                'name_en' => 'Afif',
                'name_ar' => 'عفيف',
                'district_id' => 1,
            ],
            [
                'id' => $i++,
                'name_en' => 'Ahd Al masaraha',
                'name_ar' => 'احد المسارحة',
                'district_id' => 10,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al-Aidabi',
                'name_ar' => 'العيدابي',
                'district_id' => 10,
            ],
            [
                'id' => $i++,
                'name_en' => 'hroob',
                'name_ar' => 'هروب',
                'district_id' => 10,
            ],
            [
                'id' => $i++,
                'name_en' => 'fefaa',
                'name_ar' => 'فيفاء',
                'district_id' => 10,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al-Twal',
                'name_ar' => 'الطوال',
                'district_id' => 10,
            ],
            [
                'id' => $i++,
                'name_en' => 'Ahd Roufida',
                'name_ar' => 'احد رفيده',
                'district_id' => 6,
            ],
            [
                'id' => $i++,
                'name_en' => 'Bukayriyah',
                'name_ar' => 'البكيرية',
                'district_id' => 4,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al Ghat',
                'name_ar' => 'الغاط',
                'district_id' => 1,
            ],
            [
                'id' => $i++,
                'name_en' => 'Riyad Al Khabra',
                'name_ar' => 'الخبراء',
                'district_id' => 4,
            ],
            [
                'id' => $i++,
                'name_en' => 'Khafji',
                'name_ar' => 'الخفجي',
                'district_id' => 5,
            ],
            [
                'id' => $i++,
                'name_en' => 'Hail',
                'name_ar' => 'حائل',
                'district_id' => 8,
            ],
            [
                'id' => $i++,
                'name_en' => 'Baqa',
                'name_ar' => 'بقعاء',
                'district_id' => 8,
            ],
            [
                'id' => $i++,
                'name_en' => 'Ghazala',
                'name_ar' => 'الغزالة',
                'district_id' => 8,
            ],
            [
                'id' => $i++,
                'name_en' => 'Khulais',
                'name_ar' => 'خليص',
                'district_id' => 2,
            ],
            [
                'id' => $i++,
                'name_en' => 'AlHarq',
                'name_ar' => 'الحريق',
                'district_id' => 1,
            ],
            [
                'id' => $i++,
                'name_en' => 'Marrat',
                'name_ar' => 'مرات',
                'district_id' => 1,
            ],
            [
                'id' => $i++,
                'name_en' => 'Renne',
                'name_ar' => 'الرين',
                'district_id' => 1,
            ],
            [
                'id' => $i++,
                'name_en' => 'AlKharj',
                'name_ar' => 'الخرج',
                'district_id' => 1,
            ],
            [
                'id' => $i++,
                'name_en' => 'Khobar',
                'name_ar' => 'الخبر',
                'district_id' => 5,
            ],
            [
                'id' => $i++,
                'name_en' => 'Kherma',
                'name_ar' => 'الخرمة',
                'district_id' => 2,
            ],
            [
                'id' => $i++,
                'name_en' => 'rune',
                'name_ar' => 'رنية',
                'district_id' => 2,
            ],
            [
                'id' => $i++,
                'name_en' => 'Turbah',
                'name_ar' => 'تربة',
                'district_id' => 2,
            ],
            [
                'id' => $i++,
                'name_en' => 'Jubail',
                'name_ar' => 'الجبيل',
                'district_id' => 5,
            ],
            [
                'id' => $i++,
                'name_en' => 'Missan',
                'name_ar' => 'ميسان',
                'district_id' => 2,
            ],
            [
                'id' => $i++,
                'name_en' => 'Adm',
                'name_ar' => 'أضم',
                'district_id' => 2,
            ],
            [
                'id' => $i++,
                'name_en' => 'Bahra',
                'name_ar' => 'بحرة',
                'district_id' => 2,
            ],
            [
                'id' => $i++,
                'name_en' => 'ardyat',
                'name_ar' => 'العرضيات',
                'district_id' => 2,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al Jumum',
                'name_ar' => 'الجموم',
                'district_id' => 2,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al Kamel',
                'name_ar' => 'الكامل',
                'district_id' => 2,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al Almoeh',
                'name_ar' => 'المويه',
                'district_id' => 2,
            ], 
            [
                'id' => $i++,
                'name_en' => 'Al Majarda',
                'name_ar' => 'المجاردة',
                'district_id' => 6,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al Berk',
                'name_ar' => 'البرك',
                'district_id' => 6,
            ],
            [
                'id' => $i++,
                'name_en' => 'Tanomah',
                'name_ar' => 'تنومة',
                'district_id' => 6,
            ],
            [
                'id' => $i++,
                'name_en' => 'trib',
                'name_ar' => 'طريب',
                'district_id' => 6,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al-Harajah',
                'name_ar' => 'الحرجة',
                'district_id' => 6,
            ],
            [
                'id' => $i++,
                'name_en' => 'Barek',
                'name_ar' => 'بارق',
                'district_id' => 6,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al Majmaah',
                'name_ar' => 'المجمعة',
                'district_id' => 1,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al Madhnab',
                'name_ar' => 'المذنب',
                'district_id' => 4,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al Muzahimiyah',
                'name_ar' => 'المزاحمية',
                'district_id' => 1,
            ],
            [
                'id' => $i++,
                'name_en' => 'Katif',
                'name_ar' => 'القطيف',
                'district_id' => 5,
            ],
            [
                'id' => $i++,
                'name_en' => 'Ramah',
                'name_ar' => 'رماح',
                'district_id' => 1,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al Qunfidhah',
                'name_ar' => 'القنفذة',
                'district_id' => 2,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al Qurayyat',
                'name_ar' => 'القريات',
                'district_id' => 13,
            ],
            [
                'id' => $i++,
                'name_en' => 'Dumat Al-Jandal',
                'name_ar' => 'دومة الجندل',
                'district_id' => 13,
            ],
            [
                'id' => $i++,
                'name_en' => 'Tabarjal',
                'name_ar' => 'طبرجل',
                'district_id' => 13,
            ],
            [
                'id' => $i++,
                'name_en' => 'laith',
                'name_ar' => 'الليث',
                'district_id' => 2,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al Quwayiyah',
                'name_ar' => 'القويعية',
                'district_id' => 1,
            ],
            [
                'id' => $i++,
                'name_en' => 'Wadi Al Dawasir',
                'name_ar' => 'وادي الدواسر',
                'district_id' => 1,
            ],
            [
                'id' => $i++,
                'name_en' => 'Aflaj',
                'name_ar' => 'الأفلاج',
                'district_id' => 1,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al Wajh',
                'name_ar' => 'الوجه',
                'district_id' => 7,
            ], 
            [
                'id' => $i++,
                'name_en' => 'An Naghayriyah',
                'name_ar' => 'النعيرية',
                'district_id' => 5,
            ],
            [
                'id' => $i++,
                'name_en' => 'Arar',
                'name_ar' => 'عرعر',
                'district_id' => 9,
            ],
            [
                'id' => $i++,
                'name_en' => 'Rass',
                'name_ar' => 'الرس',
                'district_id' => 4,
            ],
            [
                'id' => $i++,
                'name_en' => 'As Sulayyil',
                'name_ar' => 'السليل',
                'district_id' => 1,
            ],
            [
                'id' => $i++,
                'name_en' => 'Dharma',
                'name_ar' => 'ضرما',
                'district_id' => 1,
            ],
            [
                'id' => $i++,
                'name_en' => 'Taif',
                'name_ar' => 'الطائف',
                'district_id' => 2,
            ], 
            [
                'id' => $i++,
                'name_en' => 'Al Zulfi',
                'name_ar' => 'الزلفي',
                'district_id' => 1,
            ],
            [
                'id' => $i++,
                'name_en' => 'Badr',
                'name_ar' => 'بدر',
                'district_id' => 3,
            ],
            [
                'id' => $i++,
                'name_en' => 'Bishah',
                'name_ar' => 'بيشة',
                'district_id' => 6,
            ],
            [
                'id' => $i++,
                'name_en' => 'Bisha',
                'name_ar' => 'بيش',
                'district_id' => 10,
            ],
            [
                'id' => $i++,
                'name_en' => 'Haras',
                'name_ar' => 'الحرث',
                'district_id' => 10,
            ],
            [
                'id' => $i++,
                'name_en' => 'Dammed',
                'name_ar' => 'ضمد',
                'district_id' => 10,
            ],
            [
                'id' => $i++,
                'name_en' => 'Wraith',
                'name_ar' => 'الريث',
                'district_id' => 10,
            ],
            [
                'id' => $i++,
                'name_en' => 'Farasan',
                'name_ar' => 'فرسان',
                'district_id' => 10,
            ],
            [
                'id' => $i++,
                'name_en' => 'Arida',
                'name_ar' => 'العارضة',
                'district_id' => 10,
            ],
            [
                'id' => $i++,
                'name_en' => 'Daaer',
                'name_ar' => 'الدائر',
                'district_id' => 10,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al-Darb',
                'name_ar' => 'الدرب',
                'district_id' => 10,
            ],
            [
                'id' => $i++,
                'name_en' => 'buqayq',
                'name_ar' => 'بقيق',
                'district_id' => 5,
            ],
            [
                'id' => $i++,
                'name_en' => 'Buraidah',
                'name_ar' => 'بريدة',
                'district_id' => 4,
            ],
            [
                'id' => $i++,
                'name_en' => 'Buraidah',
                'name_ar' => 'بريدة',
                'district_id' => 4,
            ],
            [
                'id' => $i++,
                'name_en' => 'Duba',
                'name_ar' => 'ضبا',
                'district_id' => 7,
            ],
            [
                'id' => $i++,
                'name_en' => 'Taima',
                'name_ar' => 'تيماء',
                'district_id' => 7,
            ], 
            [
                'id' => $i++,
                'name_en' => 'Khamis Mushayt',
                'name_ar' => 'خميس مشيط',
                'district_id' => 6,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al-Namas Mushayt',
                'name_ar' => 'النماص',
                'district_id' => 6,
            ],
            [
                'id' => $i++,
                'name_en' => 'Dhahran Al Janoub',
                'name_ar' => 'ظهران الجنوب',
                'district_id' => 6,
            ], 
            [
                'id' => $i++,
                'name_en' => 'Hawtat Bani Tamim',
                'name_ar' => 'حوطه بنى تميم',
                'district_id' => 1,
            ],
            [
                'id' => $i++,
                'name_en' => 'Khaibar',
                'name_ar' => 'خيبر',
                'district_id' => 3,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al-Ais',
                'name_ar' => 'العيص',
                'district_id' => 3,
            ],
            [
                'id' => $i++,
                'name_en' => 'Wadi Al-Fara',
                'name_ar' => 'وادي الفرع',
                'district_id' => 3,
            ],
            [
                'id' => $i++,
                'name_en' => 'Jeddah',
                'name_ar' => 'جدة',
                'district_id' => 2,
            ],
            [
                'id' => $i++,
                'name_en' => 'Muhayil',
                'name_ar' => 'محايل',
                'district_id' => 1,
            ],
            [
                'id' => $i++,
                'name_en' => 'Rabigh',
                'name_ar' => 'رابغ',
                'district_id' => 2,
            ],
            [
                'id' => $i++,
                'name_en' => 'Rafha',
                'name_ar' => 'رفحاء',
                'district_id' => 9,
            ], 
            [
                'id' => $i++,
                'name_en' => 'Sakaka',
                'name_ar' => 'سكاكا',
                'district_id' => 13,
            ],
            [
                'id' => $i++,
                'name_en' => 'Samtah',
                'name_ar' => 'صامطة',
                'district_id' => 10,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al Shakra',
                'name_ar' => 'شقراء',
                'district_id' => 1,
            ],
            [
                'id' => $i++,
                'name_en' => 'Hotat Bani Tamim',
                'name_ar' => 'حوطة بني تميم',
                'district_id' => 1,
            ],
            [
                'id' => $i++,
                'name_en' => 'Sharurah',
                'name_ar' => 'شروره',
                'district_id' => 11,
            ],
            [
                'id' => $i++,
                'name_en' => 'Badr Al Janoub',
                'name_ar' => 'بدر الجنوب',
                'district_id' => 11,
            ],
            [
                'id' => $i++,
                'name_en' => 'yadamme',
                'name_ar' => 'يدمه',
                'district_id' => 11,
            ],
            [
                'id' => $i++,
                'name_en' => 'Thar',
                'name_ar' => 'ثار',
                'district_id' => 11,
            ],
            [
                'id' => $i++,
                'name_en' => 'Khubash',
                'name_ar' => 'خباش',
                'district_id' => 11,
            ],
            [
                'id' => $i++,
                'name_en' => 'Habouna',
                'name_ar' => 'حبونا',
                'district_id' => 11,
            ],
            [
                'id' => $i++,
                'name_en' => 'Thadij',
                'name_ar' => 'ثادق',
                'district_id' => 1,
            ],
            [
                'id' => $i++,
                'name_en' => 'Huraymila',
                'name_ar' => 'حريملاء',
                'district_id' => 1,
            ],
            [
                'id' => $i++,
                'name_en' => 'karyat el alya',
                'name_ar' => 'قريه العليا',
                'district_id' => 5,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al Udeid',
                'name_ar' => 'العديد',
                'district_id' => 5,
            ],
            [
                'id' => $i++,
                'name_en' => 'sbia',
                'name_ar' => 'صبيا',
                'district_id' => 10,
            ], 
            [
                'id' => $i++,
                'name_en' => 'Al Shanan',
                'name_ar' => 'الشنان',
                'district_id' => 8,
            ], 
            [
                'id' => $i++,
                'name_en' => 'Al haat',
                'name_ar' => 'الحائط',
                'district_id' => 8,
            ], 
            [
                'id' => $i++,
                'name_en' => 'Sulaimi',
                'name_ar' => 'السليمي',
                'district_id' => 8,
            ], 
            [
                'id' => $i++,
                'name_en' => 'shamli',
                'name_ar' => 'الشملي',
                'district_id' => 8,
            ], 
            [
                'id' => $i++,
                'name_en' => 'Muqaq',
                'name_ar' => 'موقق',
                'district_id' => 8,
            ], 
            [
                'id' => $i++,
                'name_en' => 'Samira',
                'name_ar' => 'سميراء',
                'district_id' => 8,
            ], 
            [
                'id' => $i++,
                'name_en' => 'Ras Tannurah',
                'name_ar' => 'راس تنورة',
                'district_id' => 5,
            ],
            [
                'id' => $i++,
                'name_en' => 'Tathlith',
                'name_ar' => 'تثليث',
                'district_id' => 6,
            ],
            [
                'id' => $i++,
                'name_en' => 'Balqarn',
                'name_ar' => 'بلقرن',
                'district_id' => 6,
            ],
            [
                'id' => $i++,
                'name_en' => 'Rijal Almaa',
                'name_ar' => 'رجال ألمع',
                'district_id' => 6,
            ],
            [
                'id' => $i++,
                'name_en' => 'Sarat Abidah',
                'name_ar' => 'سراة عبيدة',
                'district_id' => 6,
            ],
            [
                'id' => $i++,
                'name_en' => 'Turbah',
                'name_ar' => 'تربه',
                'district_id' => 2,
            ],
            [
                'id' => $i++,
                'name_en' => 'Turayf',
                'name_ar' => 'طريف',
                'district_id' => 9,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al-Awaqilah',
                'name_ar' => 'العويقيلة',
                'district_id' => 9,
            ], 
            [
                'id' => $i++,
                'name_en' => 'Unaizah',
                'name_ar' => 'عنيزة',
                'district_id' => 4,
            ],
            [
                'id' => $i++,
                'name_en' => 'squalid',
                'name_ar' => 'ضرية',
                'district_id' => 4,
            ],
            [
                'id' => $i++,
                'name_en' => 'Ash Shimasiyah',
                'name_ar' => 'الشماسية',
                'district_id' => 4,
            ],
            [
                'id' => $i++,
                'name_en' => 'Oyoun Al-Jawa',
                'name_ar' => 'عيون الجواء',
                'district_id' => 4,
            ], 
            [
                'id' => $i++,
                'name_en' => 'Uqlat Al-Suqur',
                'name_ar' => 'عقلة الصقور',
                'district_id' => 4,
            ],
            [
                'id' => $i++,
                'name_en' => 'Yanbu',
                'name_ar' => 'ينبع',
                'district_id' => 3,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al Ula',
                'name_ar' => 'العلا',
                'district_id' => 3,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al Mahd',
                'name_ar' => 'المهد',
                'district_id' => 3,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al Hanakia',
                'name_ar' => 'الحناكية',
                'district_id' => 3,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al Bahah',
                'name_ar' => 'الباحة',
                'district_id' => 12,
            ],
            [
                'id' => $i++,
                'name_en' => 'Baljurashi',
                'name_ar' => 'بلجرشي',
                'district_id' => 12,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al Mandaq',
                'name_ar' => 'المندق',
                'district_id' => 12,
            ],
            [
                'id' => $i++,
                'name_en' => 'Almakhwah',
                'name_ar' => 'المخواة',
                'district_id' => 12,
            ],
            [
                'id' => $i++,
                'name_en' => 'Qilwah',
                'name_ar' => 'قلوة',
                'district_id' => 12,
            ],
            [
                'id' => $i++,
                'name_en' => 'akek',
                'name_ar' => 'العقيق',
                'district_id' => 12,
            ],
            [
                'id' => $i++,
                'name_en' => 'koraa',
                'name_ar' => 'القرى',
                'district_id' => 12,
            ],
            [
                'id' => $i++,
                'name_en' => 'Hogra',
                'name_ar' => 'الحجرة',
                'district_id' => 12,
            ],
            [
                'id' => $i++,
                'name_en' => 'bni hassan',
                'name_ar' => 'بني حسن',
                'district_id' => 12,
            ],
            [
                'id' => $i++,
                'name_en' => 'zendad',
                'name_ar' => 'غامد الزناد',
                'district_id' => 12,
            ],
            [
                'id' => $i++,
                'name_en' => 'Medina',
                'name_ar' => 'المدينة المنورة',
                'district_id' => 3,
            ],
            [
                'id' => $i++,
                'name_en' => 'jazan',
                'name_ar' => 'جازان',
                'district_id' => 10,
            ],
            [
                'id' => $i++,
                'name_en' => 'Najran',
                'name_ar' => 'نجران',
                'district_id' => 11,
            ],
            [
                'id' => $i++,
                'name_en' => 'Riyadh',
                'name_ar' => 'الرياض',
                'district_id' => 1,
            ],
            [
                'id' => $i++,
                'name_en' => 'Tabuk',
                'name_ar' => 'تبوك',
                'district_id' => 7,
            ], 
            [
                'id' => $i++,
                'name_en' => 'Umluj',
                'name_ar' => 'أملج',
                'district_id' => 7,
            ],
            [
                'id' => $i++,
                'name_en' => 'Hakel',
                'name_ar' => 'حقل',
                'district_id' => 7,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al-Bida',
                'name_ar' => 'البدع',
                'district_id' => 7,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al Badae',
                'name_ar' => 'البدائع',
                'district_id' => 4,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al asyah',
                'name_ar' => 'الأسياح',
                'district_id' => 4,
            ],
            [
                'id' => $i++,
                'name_en' => 'Uhud Rafaida',
                'name_ar' => 'أحد رفيدة',
                'district_id' => 6,
            ],
            [
                'id' => $i++,
                'name_en' => 'Al Nabhani',
                'name_ar' => 'النبهانية',
                'district_id' => 4,
            ],
        ];
        City::insert($cities);
    }
}
